### ISSUE TITLE
Can't get this to work with computed / created

### ISSUE THREAD

**Issue by geoidesic** [posva/vuex-mock-store#68]
For some reason this seems to cause my Jest tests to break.

I'm testing a fairly simple component. If I don't mock the store, then I don't get these errors. With the mock store, the Jest tests will work provided that `this` is not referenced within `computed` or `created` (and no I'm not using arrow functions). Somehow the mock runs causes those hooks to run without `this` context.

(btw: I would have made a JsFiddle but I can't figure out how to set up Jest and Vuex and this library in JsFiddle. Maybe you could add a starting link to the new issue template?)

Here's the component code:
```
<template lang="pug">
  q-toolbar
    q-btn(flat='', dense='', round='', @click='toggleLeftDrawer', aria-label='Menu')
      q-icon(name='menu')
    q-toolbar-title
      .title Mobile Notary Register
      .subtitle
        | {{ locale }} Dev: {{ !!dev }} Desktop:
        | {{ !!$q.platform.is.desktop }} iPad:
        | {{ !!$q.platform.is.ipad }}
    v-offline.v-offline(online-class='online', offline-class='offline', @detected-condition='amIOnline')
      //- template(v-slot:[onlineSlot] slot-name="onlineSlot") 
    q-icon(:class="{'status-indicator': true,online: networkOnline,offline: !networkOnline}" name="fas fa-wifi")
    q-icon(:class="{'status-indicator': true,online: serverOnline,offline: !serverOnline}" name="fas fa-server")

</template>

<script>
  import VOffline from "v-offline";
  import { mapActions } from "vuex";
  import * as types from "src/store/mutation-types";
  export default {
    name: "ToolBar",
    components: { VOffline },
    data() {
      return {
        dev: process.env.DEV,
        locale: this.$q.lang.getLocale(),
        onlineSlot: "online",
        offlineSlot: "offline"
      };
    },
    computed: {
      networkOnline() {
        return this.$store.state.pings.networkOnline;
      },
      serverOnline() {
        return this.$store.state.pings.serverOnline;
      }
    },
    created() {
       console.log(this)
    },
```
I've tried various formats for the computed methods... i.e. as above, also with the extended `function` syntax and lastly with the get() and set() syntax – always the same result.

Here's the test:
```
import Vuex from "vuex";
import VueRouter from "vue-router";
import { mount, shallowMount, createLocalVue } from "@vue/test-utils";
import { Store } from "vuex-mock-store";
import Component from "../tool-bar.vue";
import * as All from "quasar";
import storeIndex from "src/store";
import pings from "src/store/pings";
import shared from "src/store/pings";
import _ from "lodash";

const store = new Store({
  modules: {
    pings,
    shared
  }
});
// const store = storeIndex;
const mocks = {
  $store: store
};
let wrapper;
const localVue = createLocalVue();
const { Quasar, date } = All;
const router = new VueRouter();
const components = Object.keys(All).reduce((object, key) => {
  const val = All[key];
  if (val && val.component && val.component.name != null) {
    object[key] = val;
  }
  return object;
}, {});

localVue.use(Vuex);
localVue.use(VueRouter);
localVue.use(Quasar, { components }); // , lang: langEn

describe("Component", () => {
  beforeEach(() => {
    console.log("Component test");
    wrapper = mount(Component, {
      store,
      localVue,
      router
    });
  });

  afterEach(() => {
    wrapper.destroy();
    // store.reset();
    jest.restoreAllMocks();
  });

  it("is a Vue instance", () => {
    expect(wrapper.isVueInstance()).toBeTruthy();
  });
```
Here's the error message and stack where it blows up like Wuhan:
```
  console.error node_modules/vue/dist/vue.common.dev.js:630
    [Vue warn]: Error in render: "TypeError: Cannot read property 'networkOnline' of undefined"

    found in

    ---> <ToolBar>
           <Root>

  console.error node_modules/vue/dist/vue.common.dev.js:1893
    TypeError: Cannot read property 'networkOnline' of undefined
        at VueComponent.networkOnline (/Users/me/project1/src/components/shared/tool-bar.vue:35:1)
        at Watcher.get (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4474:25)
        at Watcher.evaluate (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4579:21)
        at Proxy.computedGetter (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4828:17)
        at Proxy.render (/Users/me/project1/src/components/shared/tool-bar.vue:153:757)
        at VueComponent.Vue._render (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:3547:22)
        at VueComponent.updateComponent (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4063:21)
        at Watcher.get (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4474:25)
        at new Watcher (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4463:12)
        at mountComponent (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4070:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:9040:10)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:11940:16)
        at init (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:3121:13)
        at createComponent (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:5969:9)
        at createElm (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:5916:9)
        at VueComponent.patch [as __patch__] (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:6466:7)
        at VueComponent.Vue._update (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:3942:19)
        at VueComponent.updateComponent (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4063:10)
        at Watcher.get (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4474:25)
        at new Watcher (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4463:12)
        at mountComponent (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:4070:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:9040:10)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/me/project1/node_modules/vue/dist/vue.common.dev.js:11940:16)
        at mount (/Users/me/project1/node_modules/@vue/test-utils/dist/vue-test-utils.js:13528:21)
        at Object.<anonymous> (/Users/me/project1/src/components/shared/__tests__/tool-bar_jest.spec.js:50:15)
        at Object.asyncJestLifecycle (/Users/me/project1/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:53:37)
        at /Users/me/project1/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/Users/me/project1/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /Users/me/project1/node_modules/jest-jasmine2/build/queueRunner.js:73:41
        at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I'm not sure if this is a bug or just me doing it wrong.

**Comment by posva** [comment]
you need to pass the `mocks` object to mount like showed in the readme. Otherwise, there won't be access to `this.$store`
